# Generated by Django 4.1.5 on 2023-03-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
