# Generated by Django 4.1.5 on 2023-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=600)),
            ],
        ),
    ]
