# Generated by Django 4.1.5 on 2023-03-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_behaviorproblem'),
        ('confidence', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confidences',
            field=models.ManyToManyField(related_name='users', through='confidence.Confidence', to='problems.problemcategory'),
        ),
    ]
