# Generated by Django 4.1.5 on 2023-02-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrequizProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('problem_name', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(max_length=255)),
                ('leetcode_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('user_duration', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('completion_time', models.IntegerField()),
            ],
        ),
    ]
