# Generated by Django 4.1.5 on 2023-02-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProblems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrequizProblems',
        ),
    ]
