# Generated by Django 4.1.7 on 2023-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrequizProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=None)),
                ('problem_name', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(max_length=255)),
                ('leetcode_url', models.CharField(max_length=255)),
                ('perceived_difficulty', models.CharField(default=None, max_length=255, null=True)),
                ('completion_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
