# Generated by Django 4.1.7 on 2023-03-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequizproblem',
            name='completion_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
