# Generated by Django 4.1.7 on 2023-03-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_prequizproblem_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='prequizproblem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
