# Generated by Django 4.1.5 on 2023-02-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(max_length=255)),
                ('leetcode_url', models.CharField(max_length=255)),
            ],
        ),
    ]
