# Generated by Django 4.1.5 on 2023-02-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempts',
            name='date',
        ),
    ]
