# Generated by Django 4.1.7 on 2023-03-29 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0002_rename_achievement_name_achievementmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='achievementmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
