---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.10.0
        uses: actions/setup-python@master
        with:
          python-version: "3.10.0"

      - name: Install pipenv
        run: pip install pipenv

      - name: Tests
        run: "pipenv python3 manage.py test"

      - name: Lint
        run: "flake8"
