---
name: Checks

on: [push]

jobs:
  backend-test:
    name: Backend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: CSC301H5/finalprojectw23-jason-s-juniors
      - name: Install Requirements
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Flake
        run: pip install flake8

      - name: Install Pipenv
        run: pip install pipenv

      - name: Tests [Backend]
        run: cd backend; pipenv shell; python manage.py test

  frontend-test:
    name: Frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: CSC301H5/finalprojectw23-jason-s-juniors
      - name: Install packages
        run: |
          cd frontend
          npm install
          npm install -g eslint
          eslint --init
