---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@master
        with:
          python-version: 3.10

      - name: Install pipenv
        run: pip install pipenv

      - name: Tests
        run: "pipenv python manage.py test"

      - name: Lint
        run: "flake8"
