---
name: Checks

on: [pull_request, push]

jobs:
  backend-test:
    name: Backend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: CSC301H5/finalprojectw23-jason-s-juniors
          ref: dev
      - name: Install Requirements [Backend]
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Flake [Backend]
        run: pip install flake8

      - name: Tests [Backend]
        run: cd backend; python manage.py test

      - name: Lint [Backend]
        run: flake8

  frontend-test:
    name: Frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: CSC301H5/finalprojectw23-jason-s-juniors
          ref: dev
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
    
          
