---
name: Checks

on: [pull_request, push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: CSC301H5/finalprojectw23-jason-s-juniors
          path: backend
          ref: dev

      - name: Set up Python 3.10.0
        uses: actions/setup-python@master
        with:
          python-version: "3.10.0"

      #- name: Install pipenv
      #  run: "python -m pip install --upgrade pipenv wheel"

      #- id: cache-pipenv
      #  uses: actions/cache@v1
      #  with:
      #    path: ~/.local/share/virtualenvs
      #    key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      #- name: Install dependencies
      #  if: steps.cache-pipenv.outputs.cache-hit != 'true'
      #  run: "touch Pipfile && pipenv install --deploy --dev"

      - name: Install Flake
        run: pip install flake8

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Tests
        run: cd backend; python manage.py test

      - name: Lint
        run: flake8
