---
name: Checks

on: [pull_request, push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: CSC301H5/finalprojectw23-jason-s-juniors
          ref: dev
        run: |
          pip install -r finalprojectw23-jason-s-juniors/backend/requirements.txt

      - name: Install Flake
        run: pip install flake8

      - name: Tests
        run: cd finalprojectw23-jason-s-juniors/backend; python manage.py test

      - name: Lint
        run: flake8
